language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install lcov
  - # sudo pip install cpp-coveralls
script:
  - ./autogen.sh
  - ./coverage.sh
  - make install-strip && ls -halR /tmp/mjwm
  - time /tmp/mjwm/bin/mjwm -o automenu.default && cat automenu.default
  - time /tmp/mjwm/bin/mjwm --iconize -o automenu.iconize && cat automenu.iconize
