
/*
    This file is part of mjwm.
    Copyright (C) 2014  Chirantan Mitra <chirantan.mitra@gmail.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <sstream>
#include <ctime>

#include "messages.h"

std::string
amm::messages::help()
{
	std::stringstream stream;

	stream << "mjwm version " << AMM_VERSION <<  ", Copyright (C) 2014 Chirantan Mitra <chirantan.mitra@gmail.com>" << std::endl;
	stream << "mjwm comes with ABSOLUTELY NO WARRANTY; for details refer COPYING." << std::endl;
	stream << "This is free software, and you are welcome to redistribute it" << std::endl;
	stream << "under certain conditions; Refer COPYING for details." << std::endl;

	stream << "mjwm creates jwm's menu from (freedesktop) desktop files" << std::endl;
	stream << "  -o, --output-file [FILE]           Outfile file [Default: ./automenu]" << std::endl;
	stream << "  -i, --input-directory [DIRECTORY]  Directory to scan for '.desktop' files [Default: /usr/share/applications/]" << std::endl;
	stream << "  -a, --append-png                   Add '.png' to icon filenames" << std::endl;
	stream << "  -v, --version                      Show version" << std::endl << std::endl;
	stream << "  -h, --help                         Show this help" << std::endl << std::endl;

	stream << "Include the generated file in the rootmenu section of your ~/.jwmrc" << std::endl;
	stream << "More information at http://github.com/chiku/mjwm" << std::endl;

	return stream.str();
}

std::string
amm::messages::version()
{
	std::stringstream stream;
	stream << "mjwm " << AMM_VERSION << std::endl;
	return stream.str();
}

std::string
amm::messages::option_error()
{
	std::stringstream stream;
	stream << "Please run mjwm -h to see options" << std::endl;
	return stream.str();
}

std::string
amm::messages::autogenerated_by_amm()
{
	time_t rawtime;
	tm *timeinfo;
	char buffer[80];
	time(&rawtime);
	timeinfo = localtime (&rawtime);
	strftime (buffer, 80, "%c", timeinfo);

	std::stringstream stream;
	stream << "<!-- Autogenerated by mjwm " << AMM_VERSION << " (" << buffer << ") -->" << std::endl;
	return stream.str();
}
