/*
    This file is part of mjwm.
    Copyright (C) 2014  Chirantan Mitra <chirantan.mitra@gmail.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Based on work by insmyic <gminsm@gmail.com> http://sourceforge.net/projects/mjm
*/


#include <iostream>
#include <string>
#include <vector>
#include <getopt.h>

#include "messages.h"
#include "application_directories.h"
#include "menu.h"


int main(int argc, char *argv[])
{
	std::string directory_to_scan("/usr/share/applications/");
	std::string output_filename("./automenu");
	std::string icon_extension("");

	const char* short_options = "o:s:avh";
	const option long_options[] =
	{
		{"output-file",     required_argument, 0, 'o'},
		{"input-directory", required_argument, 0, 's'},
		{"append-png",      no_argument,       0, 'a'},
		{"version",         no_argument,       0, 'v'},
		{"help",            no_argument,       0, 'h'},
		{0, 0, 0, 0}
	};

	int chosen_option;
	int option_index = 0;

	while ((chosen_option = getopt_long(argc, argv, short_options, long_options, &option_index)) != -1) {
		switch (chosen_option) {
			case 'o':
				output_filename = optarg;
				break;

			case 's':
				directory_to_scan = optarg;
				break;

			case 'a':
				icon_extension = ".png";
				break;

			case 'v':
				std::cout << amm::messages::version();
				return 0;

			case 'h':
				std::cout << amm::messages::help();
				return 0;

			case '?':
				std::cerr << amm::messages::option_error();
				return 1;

			default:
				std::cerr << amm::messages::option_error();
				return 1;
		}
	}

	std::vector<std::string> directories_to_search;
	directories_to_search.push_back(directory_to_scan);

	std::vector<std::string> desktop_files = amm::application_directories(directories_to_search).desktop_file_names();

	amm::menu menu(desktop_files, icon_extension);
	menu.populate();
	if (!menu.is_valid()) {
		std::cerr << menu.error() << std::endl;
		return 1;
	}

	menu.sort();

	std::ofstream file(output_filename.c_str());
	file << amm::messages::autogenerated_by_amm();
	file << menu;
	file.close();

	return 0;
}
