name: Package

on:
  push:
    branches: [master]

env:
  MJWM_VERSION: 4.1.0

jobs:
  package:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y g++-multilib
      - name: Package
        run: ./package.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            mjwm-${{ env.MJWM_VERSION }}
            mjwm-${{ env.MJWM_VERSION }}.tar.gz
            mjwm-${{ env.MJWM_VERSION }}.pet
