name: C/C++ CI

on:
  push:
      branches: [ master ]

jobs:
  package:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y g++-multilib upx
      - name: Package
        run: ./package.sh
