name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          CXX: [g++, clang++]
      steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y lcov
      - name: Configure
        run: ./autogen.sh
      - name: Test with ${{ matrix.CXX }}
        run: CXX=${{ matrix.CXX }} ./coverage.sh
      - name: Build
        run: make
      - name: Install
        run: make install-strip && ls -halR /tmp/mjwm
      - name: Run without icons
        run: time /tmp/mjwm/bin/mjwm -o automenu.default && cat automenu.default
      - name: Run with icons
        run: time /tmp/mjwm/bin/mjwm --iconize -o automenu.iconize && cat automenu.iconize
      - name: Archive code coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage/
